com!       -bar  LArgs      echo interactive_lists#largs()
com!       -bar  LChanges   echo interactive_lists#lchanges()
com! -bang -bar  LLS        echo interactive_lists#lls(<bang>0)
com!       -bar  LMarks     echo interactive_lists#lmarks()
com!       -bar  LReg       echo interactive_lists#lreg()
